#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    currentdir=$(pwd)
    cd "$1"
    selected=$(pwd)
    cd "$currentdir"
else
    selected=$(find ~ -mindepth 1 -maxdepth 1 -type d | fzf )
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd "$selected"